revoke execute on function public.ustad_coin_apply(text, text, text, bigint, text, text) from anon, authenticated, public;
revoke execute on function public.ustad_coin_offer_touch() from anon, authenticated, public;
revoke execute on function public.ustad_shop_buy(text, text, bigint, text, integer, bigint) from anon, authenticated, public;
revoke execute on function public.ustad_ticket_consume(text) from anon, authenticated, public;
revoke execute on function public.ustad_ticket_grant(text, integer) from anon, authenticated, public;
revoke execute on function public.ustad_create_guest_account(text, text, text, text) from anon, authenticated, public;
revoke execute on function public.ustad_issue_fresh_session(text) from anon, authenticated, public;
revoke execute on function public.ustad_refresh_session(text, uuid) from anon, authenticated, public;
revoke execute on function public.ustad_revoke_session(uuid, text) from anon, authenticated, public;
grant execute on function public.ustad_coin_apply(text, text, text, bigint, text, text) to service_role;
grant execute on function public.ustad_shop_buy(text, text, bigint, text, integer, bigint) to service_role;
grant execute on function public.ustad_ticket_consume(text) to service_role;
grant execute on function public.ustad_ticket_grant(text, integer) to service_role;
grant execute on function public.ustad_create_guest_account(text, text, text, text) to service_role;
grant execute on function public.ustad_issue_fresh_session(text) to service_role;
grant execute on function public.ustad_refresh_session(text, uuid) to service_role;
grant execute on function public.ustad_revoke_session(uuid, text) to service_role;